### ISSUE TITLE
invoice function , transaction is going for approval , but in SBR required approval is false 

### ISSUE THREAD

**Issue by ilyashussain143** [mamillapalli/OAPF#72]
invoice function , transaction is going for approval , but in SBR required approval is false 

![image](https://user-images.githubusercontent.com/9261827/147267943-fdce86db-2ace-4963-8c6f-f053e26424f0.png)

![image](https://user-images.githubusercontent.com/9261827/147268050-9b2490c8-4ceb-47a2-8fc3-32339b23a512.png)

**Comment by mamillapalli** [comment]
that is a data issue, (directly inserted those values to the database on the initial data load for invoices), try to create an invoice from screen or from file, this issue will not happen
